language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  global:
  matrix:
    - REQUIRE=no-dev
    - REQUIRE=dev

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer --${REQUIRE} --prefer-source install

services: mongodb

script: phpunit -c app/