imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

assetic:
    node: /usr/bin/node
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jpegoptim:
            bin: /usr/bin/jpegoptim
        uglifycss:
            bin: /usr/bin/uglifycss
        uglifyjs2:
            bin: /usr/bin/uglifyjs
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
