f_devs_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

f_devs_article:
    resource: "@FDevsArticleBundle/Resources/config/routing.xml"
    prefix:   /

