jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, host: "%domain%" }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, host: "%domain%" }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, host: "%domain%" }
        - { path: ^/, role: ROLE_ADMIN, host: "admin.%domain%" }
        
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: FDevs\UserBundle\Document\User